export const MARK_META: Record<
  string,
  { label: string; icon: string; color: string; description: string }
> = {
  verifyable: {
    label: "Verifiable",
    icon: "/verifyable.png",
    color: "text-green-400",
    description:
      "The content contains factual claims that can be verified using reliable sources."
  },

  unverifyable: {
    label: "Unverifiable",
    icon: "/unverifyable.png",
    color: "text-zinc-400",
    description:
      "The content cannot be verified. It may contain random data, personal statements, or subjective opinions without factual basis."
  },

  insufficient: {
    label: "Insufficient",
    icon: "/insufficient.png",
    color: "text-yellow-400",
    description:
      "The content is verifiable in nature, but there is not enough reliable information available at the moment to reach a conclusion."
  },

  correct: {
    label: "Correct",
    icon: "/correct.png",
    color: "text-green-500",
    description:
      "The content is factually correct based on available evidence and trusted sources."
  },

  incorrect: {
    label: "Incorrect",
    icon: "/incorrect.png",
    color: "text-red-400",
    description:
      "The content is factually incorrect or contradicts reliable and verified sources."
  },

  pending: {
    label: "Pending",
    icon: "/pending.png",
    color: "text-blue-400",
    description:
      "Verification is currently in progress and a final verdict has not yet been assigned."
  },

  ai: {
    label: "AI-Generated",
    icon: "/ai.png",
    color: "text-purple-400",
    description:
      "The media appears to be generated or manipulated using artificial intelligence."
  },

  nonai: {
    label: "Non AI / Human-Generated",
    icon: "/nonai.png",
    color: "text-cyan-400",
    description:
      "The media appears to be created by a human and not generated by artificial intelligence."
  },

  uncertain: {
    label: "Uncertain",
    icon: "/uncertain.png",
    color: "text-orange-400",
    description:
      "Based on the current analysis, there is not enough reliable evidence to confidently classify the media as AI-generated or human-created."
  }
};